### PR TITLE
Fix sd4tvh for LibreELEC 8 and 9

### PR DESCRIPTION
**Pull request by gedakc**
This PR contains enhancements that address the following areas:

- Fix visibility of HDHomerun IP setting in GUI

- Fix crash in cache_artwork() with invalid Schedules Direct keys errorCode and errorMessage

- Fix relative paths and create temporary script to populate filter.cfg

- Fix tv_grab_sd4tvh settings parser for settings.xml versions 1 and 2

These problems were discovered on a Raspberry Pi 3 running LibreELEC 8.2.5 with Kodi 17.6 and Tvheadend Server 4.2 (8.2.113).

Testing of these enhancements was performed using the guidelines from the following LibreELEC.tv forum post:

[Schedules Direct for Tvheadend addon](https://forum.libreelec.tv/thread/3715-schedules-direct-for-tvheadend-addon/?postID=27764#post27764)

Successful testing was undertaken using a Raspberry Pi 3 with the following configurations:

- LibreELEC 8.2.5, Kodi 17.6, Tvheadend Server 4.2.6-7 (8.2.113),  with sd4tvh (this PR)

- LibreELEC 9.2.1, Kodi 18.6, Tvheadend Server 4.2.8-36 (9.2.0.121), with sd4tvh (this PR)

See the associated commit messages for further details.

### CODE REVIEW

**Comment by edit4ever** [comment]
Thanks for the contribution!  As I don't have an HDhomerun I can't fully test this - but I will merge and we can see if there are any reports of issues.

**Comment by Schmell** [comment]
I have HDHomerun and I will test

**Comment by gedakc** [comment]
Thank you @edit4ever for your efforts to create and maintain the sd4tvh add-on.  Thanks also @Schmell for offering to test.

Also thank you @edit4ever for tagging a new 0.3.2 release.

Would you also update the version number 0.3.2 in `addon.xml` so that both the git tag and the version of the add-on match?

This will make it easier to refer to and track a specific release in a tutorial I wrote.  For the reference to the sdtvh version see the General Observations section of [Build a Cheap PVR using Raspberry Pi 3, LibreELEC, Kodi, Tvheadend, & HDHomeRun](http://gedakc.users.sourceforge.net/display-doc.php?name=pvr-rpi-tvheadend#g).

**Comment by edit4ever** [comment]
Thanks - totally forgot to update the addon version!  Fixed now.

**Comment by gedakc** [comment]
Thanks for the prompt response.  Is there a way to make the git tag **0.3.2** line up with the change which added the version number to `addon.xml`?

**Comment by edit4ever** [comment]
I think I'll have to bump everything to 0.3.3 since the tag already exists and you can't delete it.

**Comment by gedakc** [comment]
That would be alright by me.  It will make it easier to troubleshoot if the version numbers match in the git tag and the `addon.xml` file.

**Comment by gedakc** [comment]
Thank you @edit4ever for setting the version to 0.3.3 in both `addon.xml` and the git tag.

**Pull request merged**
